import { describe, expect, it } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import {
  executeJoinedDTQLQuery,
  isJoinedDTQLQuery,
  key,
  parseDTQL,
  serializeJoinedDTQL,
  stringifyJoinedDTQL,
  type DTQLSchema,
  type ExistingRecord,
  type JoinedDTQLQuery,
  type QueryExecutor,
  type QueryRelation,
  type StructuredQuery,
} from "../src/index.js";

/*
 * Go-vs-TypeScript parity suite. Every case in test/parity/cases/*.json is run
 * through this package's engine and compared with the result the Go reference
 * engine produced (test/parity/expected.json, generated by hand with
 * tools/parity/regenerate.sh from the dalgo commit recorded in that file).
 *
 * Each case runs twice: through the generic executor, and with `scanPages` so
 * a flat aggregate join takes the streaming plan. Both must equal Go.
 *
 *  - rows must equal exactly: same order, same keys, same values; numbers are
 *    compared to within 1e-9 (absolute below 1, relative above);
 *  - when Go reports an error, TypeScript must throw as well. If Go failed
 *    while parsing (phase "parse") TypeScript must already fail in parseDTQL.
 *    Messages differ between the engines, so a case may name a substring the
 *    TypeScript message must contain ("tsError") to pin its location.
 */

type Data = Record<string, unknown>;
interface Dataset { readonly tables: Record<string, Record<string, readonly Data[]>> }
interface CaseDefinition {
  readonly name: string;
  readonly query?: unknown;
  readonly yaml?: string;
  readonly yamlFile?: string;
  readonly yamlReplace?: readonly (readonly [string, string])[];
  readonly yamlAppend?: string;
  readonly tsError?: string;
}
type Expected = { readonly rows: readonly Data[] } | { readonly error: string; readonly phase: string };
interface ExpectedFile {
  readonly dalgo: { readonly module: string; readonly version: string; readonly commit: string };
  readonly results: Record<string, Expected>;
}

const parityDirectory = new URL("./parity/", import.meta.url);

/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call -- the Node file API is untyped here (no @types/node); these two helpers are its only users. */
function readText(url: URL): string {
  const text: string = readFileSync(url, "utf8");
  return text;
}

function listFiles(url: URL): string[] {
  const names: string[] = readdirSync(url);
  return names;
}
/* eslint-enable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call */

function readJson(url: URL): unknown {
  return JSON.parse(readText(url));
}

const dataset = readJson(new URL("dataset.json", parityDirectory)) as Dataset;
const expectedFile = readJson(new URL("expected.json", parityDirectory)) as ExpectedFile;
const cases = listFiles(new URL("cases/", parityDirectory)).filter((name) => name.endsWith(".json")).sort()
  .flatMap((name) => (readJson(new URL(`cases/${name}`, parityDirectory)) as { readonly cases: readonly CaseDefinition[] }).cases);

// The test schema lists each table's fields as the union of its row keys; an
// empty table has no rows to read them from, so it declares an `id` field.
const schema: DTQLSchema = {
  tables: Object.entries(dataset.tables).flatMap(([database, tables]) => Object.entries(tables).map(([name, rows]) => {
    const fields = [...new Set(rows.flatMap((row) => Object.keys(row)))];
    return { database, name, fields: fields.length === 0 ? ["id"] : fields };
  })),
};

function document(definition: CaseDefinition): unknown {
  if (definition.yamlFile === undefined) return definition.yaml ?? definition.query;
  let text = readText(new URL(definition.yamlFile, parityDirectory));
  for (const [from, to] of definition.yamlReplace ?? []) {
    if (!text.includes(from)) throw new Error(`${definition.name}: yamlReplace ${JSON.stringify(from)} not found`);
    text = text.replace(from, to);
  }
  return text + (definition.yamlAppend ?? "");
}

function records(database: string, name: string): ExistingRecord<Data>[] {
  return (dataset.tables[database]?.[name] ?? []).map((data, index) => ({ key: key(name, String(index)), exists: true as const, data: { ...data } }));
}

function executor(database: string | undefined): QueryExecutor {
  return {
    query: <T>(query: StructuredQuery<T>) => Promise.resolve({ records: records(database ?? "chinook", query.source.name) as unknown as readonly ExistingRecord<T>[] }),
  };
}

type Outcome = { readonly rows: readonly Data[] } | { readonly error: Error; readonly phase: "parse" | "execute" };

async function run(definition: CaseDefinition, streaming: boolean): Promise<Outcome & { readonly query?: JoinedDTQLQuery }> {
  let query: JoinedDTQLQuery;
  try {
    const parsed = parseDTQL(document(definition), schema);
    if (!isJoinedDTQLQuery(parsed)) throw new Error("parity cases must use the relation model");
    query = parsed;
  } catch (error) {
    return { error: error as Error, phase: "parse" };
  }
  try {
    const options = {
      schema,
      resolveExecutor: (relation: QueryRelation) => executor(relation.database),
      ...(streaming ? { scanPages: async function* (relation: QueryRelation) { await Promise.resolve(); yield { records: records(relation.database ?? "chinook", relation.name) }; } } : {}),
    };
    const page = await executeJoinedDTQLQuery(executor(undefined), query, options);
    return { rows: page.records.map((row) => row.data), query };
  } catch (error) {
    return { error: error as Error, phase: "execute" };
  }
}

const tolerance = 1e-9;

function closeTo(actual: unknown, expected: unknown, path: string): string | undefined {
  if (typeof expected === "number" && typeof actual === "number") {
    return Math.abs(actual - expected) <= tolerance * Math.max(1, Math.abs(expected)) ? undefined : `${path}: ${String(actual)} != ${String(expected)}`;
  }
  if (Array.isArray(expected) || (typeof expected === "object" && expected !== null)) {
    if (typeof actual !== "object" || actual === null || Array.isArray(actual) !== Array.isArray(expected)) return `${path}: ${JSON.stringify(actual)} != ${JSON.stringify(expected)}`;
    const left = actual as Record<string, unknown>;
    const right = expected as Record<string, unknown>;
    const leftKeys = Object.keys(left).sort();
    const rightKeys = Object.keys(right).sort();
    if (leftKeys.join("\u0000") !== rightKeys.join("\u0000")) return `${path}: keys [${leftKeys.join(",")}] != [${rightKeys.join(",")}]`;
    for (const name of rightKeys) {
      const difference = closeTo(left[name], right[name], `${path}.${name}`);
      if (difference !== undefined) return difference;
    }
    return undefined;
  }
  return actual === expected ? undefined : `${path}: ${JSON.stringify(actual)} != ${JSON.stringify(expected)}`;
}

describe("Go parity suite", () => {
  it("records the dalgo commit the expectations were generated from", () => {
    expect(expectedFile.dalgo.module).toBe("github.com/dal-go/dalgo");
    expect(expectedFile.dalgo.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(expectedFile.dalgo.version).toMatch(/^v\d+\.\d+\.\d+/);
  });

  it("has an expectation for every case and no orphan expectations", () => {
    const names = cases.map((definition) => definition.name);
    expect(new Set(names).size).toBe(names.length);
    expect(Object.keys(expectedFile.results).sort()).toEqual([...names].sort());
  });

  describe.each([["generic executor", false], ["streaming scanPages executor", true]] as const)("%s", (_label, streaming) => {
    it.each(cases.map((definition) => [definition.name, definition] as const))("%s", async (_name, definition) => {
      const expected = expectedFile.results[definition.name];
      if (expected === undefined) throw new Error(`no expectation for ${definition.name}: run tools/parity/regenerate.sh`);
      const outcome = await run(definition, streaming);
      if ("error" in expected) {
        if (!("error" in outcome)) throw new Error(`Go fails (${expected.phase}: ${expected.error.split("\n")[0] ?? ""}) but TypeScript returned ${JSON.stringify(outcome.rows)}`);
        if (expected.phase === "parse") expect(outcome.phase, `Go rejects at parse; TypeScript failed at ${outcome.phase}: ${outcome.error.message}`).toBe("parse");
        if (definition.tsError !== undefined) expect(outcome.error.message).toContain(definition.tsError);
        return;
      }
      if ("error" in outcome) throw new Error(`Go returns rows but TypeScript failed at ${outcome.phase}: ${outcome.error.message}`);
      expect(outcome.rows).toHaveLength(expected.rows.length);
      const differences = expected.rows.map((row, index) => closeTo(outcome.rows[index], row, `row[${index.toString()}]`)).filter((difference) => difference !== undefined);
      expect(differences, `TypeScript rows ${JSON.stringify(outcome.rows)}\nGo rows ${JSON.stringify(expected.rows)}`).toEqual([]);
    });
  });

  it.each(cases.map((definition) => [definition.name, definition] as const))("round-trips %s through canonical DTQL", async (_name, definition) => {
    const outcome = await run(definition, false);
    if ("error" in outcome) return;
    const query = outcome.query;
    if (query === undefined) throw new Error("parsed query expected");
    expect(parseDTQL(stringifyJoinedDTQL(query), schema)).toEqual(query);
    expect(parseDTQL(JSON.stringify(serializeJoinedDTQL(query)), schema)).toEqual(query);
  });
});
